<?xml version="1.0" encoding="utf-8"?><Database Name="HotelDB" Class="HotelDBDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Bookings" Member="Bookings">
    <Type Name="Booking">
      <Column Name="BookingId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GuestId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CheckInDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="CheckOutDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ReservationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NumberOfGuests" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Booking_ExtraService" Member="ExtraServices" ThisKey="BookingId" OtherKey="BookingId" Type="ExtraService" />
      <Association Name="Booking_Invoice" Member="Invoices" ThisKey="BookingId" OtherKey="BookingId" Type="Invoice" />
      <Association Name="Guest_Booking" Member="Guest" ThisKey="GuestId" OtherKey="GuestId" Type="Guest" IsForeignKey="true" />
      <Association Name="Room_Booking" Member="Room" ThisKey="RoomId" OtherKey="RoomId" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ExtraServices" Member="ExtraServices">
    <Type Name="ExtraService">
      <Column Name="ExtraServiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Association Name="Booking_ExtraService" Member="Booking" ThisKey="BookingId" OtherKey="BookingId" Type="Booking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Guests" Member="Guests">
    <Type Name="Guest">
      <Column Name="GuestId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Contact" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IdentificationDocument" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Guest_Booking" Member="Bookings" ThisKey="GuestId" OtherKey="GuestId" Type="Booking" />
    </Type>
  </Table>
  <Table Name="dbo.Invoices" Member="Invoices">
    <Type Name="Invoice">
      <Column Name="InvoiceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IssueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="StayTotal" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="ExtrasTotal" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="PaymentMethod" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,0) NOT NULL" CanBeNull="false" />
      <Association Name="Booking_Invoice" Member="Booking" ThisKey="BookingId" OtherKey="BookingId" Type="Booking" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Rooms" Member="Rooms">
    <Type Name="Room">
      <Column Name="RoomId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PricePerNight" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Room_Booking" Member="Bookings" ThisKey="RoomId" OtherKey="RoomId" Type="Booking" />
    </Type>
  </Table>
</Database>